FROM archlinux:latest

ENV container docker
ENV pip_packages "ansible"

# Install packages
RUN pacman -Syu --noconfirm \
  && pacman -S --noconfirm \
  sudo \
  which \
  python \
  python-pip \
  && pacman -Sc --noconfirm

# Install Ansible
RUN pip install $pip_packages

# Install Ansible inventory file
RUN mkdir -p /etc/ansible \
  && echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd", "--system"]